products = [
    {
      '_id': '1',
      'name': 'A Little Life',
      'image': '/images/a-little-life.jpg',
      'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      'brand': 'Apple',
      'category': 'Books',
      'price': 89.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Citizen: An American Lyric',
      'image': '/images/citizen-an-american-lyric.jpg',
      'description':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      'brand': 'Apple',
      'category': 'Books',
      'price': 599.99,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Geek Love',
      'image': '/images/geek-love.jpg',
      'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      'brand': 'Cannon',
      'category': 'Books',
      'price': 929.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'I Am in Bed With You',
      'image': '/images/i-am-in-bed-with-you.jpg',
      'description':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      'brand': 'Sony',
      'category': 'Books',
      'price': 399.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Mrs Caliban',
      'image': '/images/mrs-caliban.jpg',
      'description':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      'brand': 'Logitech',
      'category': 'Books',
      'price': 49.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'The Book of Night Women',
      'image': '/images/the-book-of-night-women.jpg',
      'description':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      'brand': 'Amazon',
      'category': 'Books',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'The Killing Moon',
        'image': '/images/the-killing-moon.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Books',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
      {
        '_id': '8',
        'name': 'Why Are All the Black Kids Sitting Together in the Cafeteria',
        'image': '/images/why-are-all-the-black-kids-sitting-together-in-the-cafeteria.jpg',
        'description':
          'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Books',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
      },
  ]
